In [0]:
import numpy as np

def nonlin(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)

	return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])

np.random.seed(1)

In [3]:
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
print ("initialized weights -> syn0:")
print (syn0)
print ("initialized weights -> syn1:")
print (syn1)

initialized weights -> syn0:
[[-0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523]
 [ 0.7527783   0.78921333 -0.82991158 -0.92189043]]
initialized weights -> syn1:
[[-0.66033916]
 [ 0.75628501]
 [-0.80330633]
 [-0.15778475]]


In [11]:
for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print("ITERATION:", j)
        print("l2_error:")
        print(l2_error)
        print("Error:" + str(np.mean(np.abs(l2_error))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

ITERATION: 0
l2_error:
[[-0.00090556]
 [ 0.00241423]
 [ 0.00288122]
 [-0.00329236]]
Error:0.00237334241680298
ITERATION: 10000
l2_error:
[[-0.00087839]
 [ 0.00234875]
 [ 0.00280373]
 [-0.00320383]]
Error:0.0023086737762318026
ITERATION: 20000
l2_error:
[[-0.00085337]
 [ 0.00228829]
 [ 0.00273216]
 [-0.00312208]]
Error:0.0022489753367699048
ITERATION: 30000
l2_error:
[[-0.00083026]
 [ 0.00223224]
 [ 0.00266581]
 [-0.00304627]]
Error:0.0021936428879338276
ITERATION: 40000
l2_error:
[[-0.00080881]
 [ 0.0021801 ]
 [ 0.00260405]
 [-0.00297572]]
Error:0.002142170176549496
ITERATION: 50000
l2_error:
[[-0.00078884]
 [ 0.00213143]
 [ 0.00254639]
 [-0.00290986]]
Error:0.00209412940396447
