<a href="https://colab.research.google.com/github/bartosz-paternoga/ML_algos_py/blob/master/Basic_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [0]:
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])


In [33]:
#output dataset            
y = np.array([[0,0,1,1]]).T
print(y)

[[0]
 [0]
 [1]
 [1]]


In [0]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

In [35]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
print ("initialized weights -> syn0:")
print (syn0)

initialized weights -> syn0:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [36]:
for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)

print ("final weigths -> syn0:")
print (syn0)

Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
final weigths -> syn0:
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
