In [0]:
import numpy as np

def nonlin(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)

	return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])

np.random.seed(1)

In [0]:
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
print ("initialized weights -> syn0:")
print (syn0)
print ("initialized weights -> syn1:")
print (syn1)

initialized weights -> syn0:
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
initialized weights -> syn1:
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


In [0]:
for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
        print("ITERATION:", j)
        print("l2_error:")
        print("--------------------------------")
        print(l2_error)
        print("--------------------------------")
        print("Error:" + str(np.mean(np.abs(l2_error))))
        print("--------------------------------")
        print("l1")
        print(l1)
        print("--------------------------------")
        print("l2")
        print(l2)
        print("--------------------------------")
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)
    
    if (j% 10000) == 0:
        print("l2_delta")
        print(l2_delta)
        print("--------------------------------")
        print("l1_error")
        print(l1_error)
        print("--------------------------------")
        print("l1_delta")
        print(l1_delta)
        print("--------------------------------")

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
    if (j% 10000) == 0:
        print("syn1")
        print(syn1)
        print("--------------------------------")
        print("syn0")
        print(syn0)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ITERATION: 0
l2_error:
--------------------------------
[[-0.00126577]
 [ 0.00155634]
 [ 0.00146269]
 [-0.00185586]]
--------------------------------
Error:0.0015351637196967173
--------------------------------
l1
[[7.78098095e-01 1.04016846e-01 9.31429687e-01 9.98078949e-01]
 [1.44791781e-01 2.82107532e-04 1.56690141e-02 9.03959896e-01]
 [9.97983901e-01 9.07728043e-01 2.06265251e-02 8.64525810e-01]
 [9.59840464e-01 2.33537531e-02 2.46804789e-05 1.03628668e-01]]
--------------------------------
l2
[[0.00126577]
 [0.99844366]
 [0.99853731]
 [0.00185586]]
--------------------------------
l2_delta
[[-1.60014827e-06]
 [ 2.41842832e-06]
 [ 2.13632252e-06]
 [-3.43780988e-06]]
--------------------------------
l1_error
[[ 1.22607261e-05 -1.23270909e-05  1.72762825e-05 -1.37015055e-05]
 [-1.85305873e-05  1.86308896e-05 -2.61109872e-05  2.07081492e-05]
 [-1.63690239e-05  1.64576261e-05 -2.30651823e