In [0]:
import numpy as np

In [0]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [0]:
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])


In [65]:
#output dataset            
y = np.array([[0,0,1,1]]).T
print(y)

[[0]
 [0]
 [1]
 [1]]


In [0]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

In [67]:
# initialize weights randomly with mean 0
w = 2*np.random.random((3,1)) - 1
print ("initialized weights -> syn0:")
print (w)

initialized weights -> syn0:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [68]:
for iter in range(3):
    
    print("ITER:", iter)  
    
    # forward propagation
    dotProd = np.dot(l0,w)
    l0 = X
    l1 = nonlin(np.dot(l0,w))
    print("l0") 
    print(l0) 
    print("np.dot(l0,w)") 
    print(dotProd) 
    print("l1") 
    print(l1) 

    # how much did we miss?
    l1_error = y - l1
    print("l1_error") 
    print(l1_error) 
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    deriv = nonlin(l1,True)
    l1_delta = l1_error * nonlin(l1,True)
    print("deriv") 
    print(deriv) 
    print("l1_delta") 
    print(l1_delta) 
    
    
    # update weights
    w += np.dot(l0.T,l1_delta)
    print("l0.T") 
    print(l0.T) 
    print ("Output after single iteration:")
    print (l1)
    print ("Weigths after single iteration:")
    print (w)


print ("Output After Training:")
print (l1)

print ("final weigths -> syn0:")
print (w)

ITER: 0
l0
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
np.dot(l0,w)
[[-0.99977125]
 [-0.55912226]
 [-1.16572724]
 [-0.72507825]]
l1
[[0.2689864 ]
 [0.36375058]
 [0.23762817]
 [0.3262757 ]]
l1_error
[[-0.2689864 ]
 [-0.36375058]
 [ 0.76237183]
 [ 0.6737243 ]]
deriv
[[0.19663272]
 [0.23143609]
 [0.18116102]
 [0.21981987]]
l1_delta
[[-0.05289153]
 [-0.08418501]
 [ 0.13811206]
 [ 0.14809799]]
l0.T
[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]
Output after single iteration:
[[0.2689864 ]
 [0.36375058]
 [0.23762817]
 [0.3262757 ]]
Weigths after single iteration:
[[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]
ITER: 1
l0
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
np.dot(l0,w)
[[-0.85063774]
 [-0.34607578]
 [-0.73038368]
 [-0.22582172]]
l1
[[0.29929909]
 [0.41433436]
 [0.32511054]
 [0.44378327]]
l1_error
[[-0.29929909]
 [-0.41433436]
 [ 0.67488946]
 [ 0.55621673]]
deriv
[[0.20971915]
 [0.2426614 ]
 [0.21941368]
 [0.24683968]]
l1_delta
[[-0.06276875]
 [-0.10054295]
 [ 0.14807998]
 [ 0.13729636]]
l0.T
[[0 0 1 1]
 [0 1 0 1