In [48]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x 
  
def relu2deriv(output):
    return output>0  
  
streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ] ] )

print("streetlights","\n", streetlights,"\n")

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

print("walk_vs_stop","\n",walk_vs_stop,"\n")
    
alpha = 0.2
hidden_size = 4

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

print("weights_0_1","\n",weights_0_1,"\n")
print("weights_1_2","\n",weights_1_2,"\n")


for iteration in range(60):
   layer_2_error = 0
   for i in range(len(streetlights)):
      print("i:",i,"\n")
      layer_0 = streetlights[i:i+1]
      print("layer_0","\n",layer_0,"\n")
      layer_1 = relu(np.dot(layer_0,weights_0_1))
      print("layer_1 before relu","\n",np.dot(layer_0,weights_0_1),"\n")
      layer_2 = np.dot(layer_1,weights_1_2)
      print("layer_2","\n",layer_2,"\n")
      
      layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
      print("layer_2_error","\n",layer_2_error,"\n")
      
      layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])
      print("layer_2_delta","\n",layer_2_delta,"\n")
      layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
      print("relu2deriv(layer_1)","\n",relu2deriv(layer_1),"\n")
      print("layer_1_delta no relu","\n",layer_2_delta.dot(weights_1_2.T),"\n")
      print("layer_1_delta","\n",layer_1_delta,"\n")
      
      weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
      print("weights_1_2","\n",weights_1_2,"\n")
      weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)
      print("weights_0_1","\n",weights_0_1,"\n")
      
   if(iteration % 10 == 9):
      print("iteration",iteration)
      print("Error:" + str(layer_2_error),"\n")




streetlights 
 [[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]] 

walk_vs_stop 
 [[1]
 [1]
 [0]
 [0]] 

weights_0_1 
 [[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]] 

weights_1_2 
 [[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]] 

i: 0 

layer_0 
 [[1 0 1]] 

layer_1 before relu 
 [[-0.37242104  0.51828245 -1.16138222 -0.02489585]] 

layer_1 after relu 
 [[-0.          0.51828245 -0.         -0.        ]] 

layer_2 
 [[0.39194327]] 

layer_2_error 
 0.3697329913497495 

layer_2_delta 
 [[-0.60805673]] 

relu2deriv(layer_1) 
 [[False  True False False]] 

layer_1_delta no relu 
 [[ 0.3594196  -0.45983371  0.57475031 -0.20730783]] 

layer_1_delta 
 [[ 0.         -0.45983371  0.         -0.        ]] 

weights_1_2 
 [[-0.5910955 ]
 [ 0.8192639 ]
 [-0.94522481]
 [ 0.34093502]] 

weights_0_1 
 [[-0.16595599  0.53261573 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.